export {
  q8Multiply,
  q8Conjugate,
  q8Inverse,
  q8Norm,
  quaternionToQ8,
  q8ToQuaternion,
  q8Distance,
  q8ShortestPath,
  Q8CognitiveStateMachine,
  Q8_TABLE,
  Q8_STATES,
  type Q8Element,
  type Q8State,
} from "./quaternion-group";

export {
  complexAdd,
  complexMul,
  complexScale,
  matMul,
  matTensor,
  trace,
  measurePauli,
  createSuperposition,
  collapseToBasis,
  blochSphere,
  pauliToQ8,
  PAULI_SET,
  PAULI_X,
  PAULI_Y,
  PAULI_Z,
  PAULI_I,
  type PauliMatrix,
  type Complex,
  type QuantumCognitiveState,
} from "./pauli-matrices";
