/**
 * Multilingual keyword aliases — maps keywords in 6 languages to Vietnamese intent domains.
 * Used by the NLP classifier to match foreign-language queries to the correct heuristic path.
 */

export const MULTILINGUAL_KEYWORDS: Record<string, string[]> = {
  STATISTICS: [
    "probability",
    "variance",
    "standard deviation",
    "mean",
    "median",
    "mode",
    "covariance",
    "pearson",
    "correlation",
    "shannon",
    "diversity",
    "kalman",
    "filter",
    " xác suất",
    "phương sai",
    "độ lệch chuẩn",
    "trung bình",
    "trung vị",
    "yếu vị",
    "hiệp phương sai",
    "tương quan",
    "shannon",
    "đa dạng",
    "kalman",
    "lọc",
    "確率",
    "分散",
    "標準偏差",
    "シャノン",
    "カルマン",
    "概率",
    "方差",
    "标准差",
    "香农",
    "卡尔曼",
    "Wahrscheinlichkeit",
    "Varianz",
    "Standardabweichung",
    "todennäköisyys",
    "varianssi",
    "keskihajonta",
    "הסתברות",
    "שונות",
    "סטיית תקן",
  ],
  FORECAST: [
    "forecast",
    "arima",
    "time series",
    "predict",
    "prediction",
    "prophet",
    "dự báo",
    "chuỗi thời gian",
    "dự đoán",
    "xu hướng",
    "予測",
    "時系列",
    "预测",
    "时间序列",
    "预报",
    "Vorhersage",
    "Zeitreihe",
    "Prognose",
    "ennuste",
    "aikasarja",
    "ennustaa",
    "חיזוי",
    "סדרת זמן",
  ],
  ACADEMIC: [
    "math",
    "equation",
    "formula",
    "theorem",
    "proof",
    "solve",
    "calculate",
    "toán",
    "công thức",
    "định lý",
    "chứng minh",
    "giải",
    "tính",
    "数学",
    "方程式",
    "公式",
    "定理",
    "解",
    "Mathematik",
    "Gleichung",
    "Formel",
    "Theorem",
    "matematiikka",
    "yhtälö",
    "kaava",
    "מתמטיקה",
    "משוואה",
    "נוסחה",
  ],
  GRAPH: [
    "graph",
    "tsp",
    "max flow",
    "min cut",
    "network",
    "dijkstra",
    "shortest path",
    "đồ thị",
    "đường ngắn nhất",
    "luồng",
    "mạng",
    "đỉnh",
    "cạnh",
    "グラフ",
    "最短経路",
    "图",
    "最短路径",
    "网络",
    "Graph",
    "Kürzester Weg",
    "Netzwerk",
    "graafi",
    "lyhin reitit",
    "verkosto",
    "גרף",
    "מסלול קצר",
  ],
  MARKET: [
    "price",
    "market",
    "sell",
    "buy",
    "revenue",
    "profit",
    "cost",
    "trade",
    "giá",
    "thị trường",
    "bán",
    "mua",
    "doanh thu",
    "lợi nhuận",
    "chi phí",
    "giao dịch",
    "価格",
    "市場",
    "売買",
    "収益",
    "价格",
    "市场",
    "买卖",
    "收入",
    "利润",
    "Preis",
    "Markt",
    "kaufen",
    "verkaufen",
    "Umsatz",
    "hinta",
    "markkina",
    "myydä",
    "ostaa",
    "voitto",
    "מחיר",
    "שוק",
    "מכירה",
    "קניה",
  ],
  REASONING: [
    "react",
    "chain of thought",
    "agentic",
    "workflow",
    "reasoning",
    "logic",
    "suy luận",
    "tư duy",
    "luồng công việc",
    "chiến lược",
    "推論",
    "思考連鎖",
    "推理",
    "思维链",
    "工作流",
    "Reasoning",
    "Denkweise",
    "Workflow",
    "päättely",
    "ajatukset",
    "työvoima",
    "היגיון",
    "שרשרת מחשבה",
  ],
  SALES: [
    "product",
    "order",
    "cart",
    "inventory",
    "shipping",
    "customer",
    "sản phẩm",
    "đặt hàng",
    "giỏ hàng",
    "kho",
    "vận chuyển",
    "khách hàng",
    "商品",
    "注文",
    "カート",
    "在庫",
    "产品",
    "订单",
    "购物车",
    "库存",
    "Produkt",
    "Bestellung",
    "Warenkorb",
    "Lager",
    "tuote",
    "tilaus",
    "ostoskori",
    "varasto",
    "מוצר",
    "הזמנה",
    "עגלה",
    "מלאי",
  ],
  WEATHER: [
    "weather",
    "temperature",
    "rain",
    "humidity",
    "forecast weather",
    "climate",
    "thời tiết",
    "nhiệt độ",
    "mưa",
    "độ ẩm",
    "khí hậu",
    "天気",
    "気温",
    "雨",
    "湿度",
    "天气",
    "温度",
    "降雨",
    "湿度",
    "Wetter",
    "Temperatur",
    "Regen",
    "Feuchtigkeit",
    "sää",
    "lämpötila",
    "sade",
    "kosteus",
    "מזג אוויר",
    "טמפרטורה",
    "גשם",
    "לחות",
  ],
  GREET: [
    "hello",
    "hi",
    "hey",
    "good morning",
    "good afternoon",
    "good evening",
    "xin chào",
    "chào",
    "chào bạn",
    "chào sếp",
    "こんにちは",
    "はじめまして",
    "おはよう",
    "你好",
    "早上好",
    "下午好",
    "Hallo",
    "Guten Tag",
    "Guten Morgen",
    "hei",
    "moi",
    "hyvää huomenta",
    "שלום",
    "בוקר טוב",
  ],
};

/**
 * Match a foreign-language query against multilingual keyword map.
 * Returns the best matching intent or null.
 */
export function matchMultilingualIntent(query: string): { intent: string; score: number } | null {
  const q = query
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
  const qWords = new Set(q.split(/\s+/).filter((w) => w.length > 1));

  let bestIntent: string | null = null;
  let bestScore = 0;

  for (const [intent, keywords] of Object.entries(MULTILINGUAL_KEYWORDS)) {
    let matches = 0;
    for (const kw of keywords) {
      const kwLower = kw
        .toLowerCase()
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .toLowerCase();
      if (q.includes(kwLower) || qWords.has(kwLower)) {
        matches++;
      }
    }
    const score = matches / keywords.length;
    if (score > bestScore && score >= 0.05) {
      bestScore = score;
      bestIntent = intent;
    }
  }

  return bestIntent ? { intent: bestIntent, score: bestScore } : null;
}
