name: Deploy to Cloudflare Pages


on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest


      - name: Install Dependencies
        run: bun install --no-frozen-lockfile


      - name: Build Project
        run: bun run build


      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: rottra
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main

